// swift-tools-version: 6.1
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

// Strict concurrency and warnings-as-errors everywhere. The engine is a
// validation library: a warning is a defect that has not been read yet.
let strictSwiftSettings: [SwiftSetting] = [
    .enableUpcomingFeature("ExistentialAny"),
    .enableUpcomingFeature("InternalImportsByDefault"),
]

let package = Package(
    name: "BusinessID",
    platforms: [
        .macOS(.v13),
        .iOS(.v16),
        .tvOS(.v16),
        .watchOS(.v9),
    ],
    products: [
        // The shipped engine: generated code, the primitives it calls, and a
        // hand written API. It has no dependency and never decodes a bundle.
        .library(name: "BusinessID", targets: ["BusinessID"]),
        // Build time tool. Reads `businessid-rules.binpb`, applies the twenty
        // five load checks and emits Swift. Never shipped to a consumer.
        .executable(name: "businessid-gen", targets: ["businessid-gen"]),
        // Conformance testee, driven by the runner over stdin/stdout.
        .executable(name: "businessid-testee", targets: ["businessid-testee"]),
    ],
    dependencies: [
        .package(url: "https://github.com/apple/swift-protobuf.git", from: "1.38.1"),
    ],
    targets: [
        // MARK: - Shipped engine

        .target(
            name: "BusinessID",
            swiftSettings: strictSwiftSettings
        ),

        // MARK: - Generator (build time only)

        // Protobuf code generated by protoc-gen-swift from proto/. Never
        // edited by hand, never public: `package` visibility keeps it reachable
        // by the generator and the conformance plumbing and by nothing else.
        .target(
            name: "BusinessIDWire",
            dependencies: [.product(name: "SwiftProtobuf", package: "swift-protobuf")]
        ),
        .target(
            name: "BusinessIDGenerator",
            dependencies: [
                "BusinessIDWire",
                .product(name: "SwiftProtobuf", package: "swift-protobuf"),
            ],
            swiftSettings: strictSwiftSettings
        ),
        .executableTarget(
            name: "businessid-gen",
            dependencies: ["BusinessIDGenerator"],
            swiftSettings: strictSwiftSettings
        ),

        // MARK: - Conformance plumbing (never shipped)

        .target(
            name: "BusinessIDTestee",
            dependencies: [
                "BusinessID",
                "BusinessIDGenerator",
                "BusinessIDWire",
                .product(name: "SwiftProtobuf", package: "swift-protobuf"),
            ],
            swiftSettings: strictSwiftSettings
        ),
        .executableTarget(
            name: "businessid-testee",
            dependencies: ["BusinessIDTestee"],
            swiftSettings: strictSwiftSettings
        ),
        .target(
            name: "BusinessIDConformance",
            dependencies: [
                "BusinessIDTestee",
                "BusinessIDWire",
                .product(name: "SwiftProtobuf", package: "swift-protobuf"),
            ],
            swiftSettings: strictSwiftSettings
        ),
        .executableTarget(
            name: "businessid-conformance-runner",
            dependencies: ["BusinessIDConformance"],
            swiftSettings: strictSwiftSettings
        ),

        // MARK: - Tests

        .testTarget(
            name: "BusinessIDTests",
            dependencies: ["BusinessID"],
            swiftSettings: strictSwiftSettings
        ),
        .testTarget(
            name: "BusinessIDGeneratorTests",
            dependencies: ["BusinessIDGenerator"],
            swiftSettings: strictSwiftSettings
        ),
        .testTarget(
            name: "BusinessIDConformanceTests",
            dependencies: ["BusinessIDConformance"],
            swiftSettings: strictSwiftSettings
        ),
    ]
)
