// swift-tools-version: 6.1
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

// Strict concurrency and warnings-as-errors everywhere. The engine is a
// validation library: a warning is a defect that has not been read yet.
let strictSwiftSettings: [SwiftSetting] = [
    .enableUpcomingFeature("ExistentialAny"),
    .enableUpcomingFeature("InternalImportsByDefault"),
]

let package = Package(
    name: "EntID",
    platforms: [
        .macOS(.v13),
        .iOS(.v16),
        .tvOS(.v16),
        .watchOS(.v9),
    ],
    products: [
        // The shipped engine: generated code, the primitives it calls, and a
        // hand written API. It has no dependency and never decodes a bundle.
        .library(name: "EntID", targets: ["EntID"]),
        // Build time tool. Reads `entid-rules.binpb`, applies the twenty
        // five load checks and emits Swift. Never shipped to a consumer.
        .executable(name: "entid-gen", targets: ["entid-gen"]),
        // Conformance testee, driven by the runner over stdin/stdout.
        .executable(name: "entid-testee", targets: ["entid-testee"]),
    ],
    dependencies: [
        .package(url: "https://github.com/apple/swift-protobuf.git", from: "1.38.1")
    ],
    targets: [
        // MARK: - Shipped engine

        .target(
            name: "EntID",
            swiftSettings: strictSwiftSettings
        ),

        // MARK: - Generator (build time only)

        // Protobuf code generated by protoc-gen-swift from proto/. Never
        // edited by hand, never public: `package` visibility keeps it reachable
        // by the generator and the conformance plumbing and by nothing else.
        .target(
            name: "EntIDWire",
            dependencies: [.product(name: "SwiftProtobuf", package: "swift-protobuf")]
        ),
        .target(
            name: "EntIDGenerator",
            dependencies: [
                "EntIDWire",
                .product(name: "SwiftProtobuf", package: "swift-protobuf"),
            ],
            swiftSettings: strictSwiftSettings
        ),
        .executableTarget(
            name: "entid-gen",
            dependencies: ["EntIDGenerator"],
            swiftSettings: strictSwiftSettings
        ),

        // MARK: - The testee (never shipped)
        //
        // The conformance runner is not here and never will be. It comes from
        // the specification repository, pinned to the commit `rules.lock`
        // records, so that a corpus is never judged by a comparator an engine
        // wrote for itself. What this package provides is the testee, and the
        // tests proving it does not cheat.

        .target(
            name: "EntIDTestee",
            dependencies: [
                "EntID",
                "EntIDGenerator",
                "EntIDWire",
                .product(name: "SwiftProtobuf", package: "swift-protobuf"),
            ],
            swiftSettings: strictSwiftSettings
        ),
        .executableTarget(
            name: "entid-testee",
            dependencies: ["EntIDTestee"],
            swiftSettings: strictSwiftSettings
        ),

        // MARK: - Development tools, never products

        .executableTarget(
            name: "entid-fuzz",
            dependencies: ["EntID", "EntIDGenerator"],
            swiftSettings: strictSwiftSettings
        ),
        .executableTarget(
            name: "entid-bench",
            dependencies: ["EntID", "EntIDGenerator"],
            swiftSettings: strictSwiftSettings
        ),

        // MARK: - Tests

        .testTarget(
            name: "EntIDTests",
            dependencies: ["EntID"],
            swiftSettings: strictSwiftSettings
        ),
        .testTarget(
            name: "EntIDGeneratorTests",
            dependencies: [
                "EntIDGenerator",
                "EntIDWire",
                .product(name: "SwiftProtobuf", package: "swift-protobuf"),
            ],
            swiftSettings: strictSwiftSettings
        ),
        .testTarget(
            name: "EntIDTesteeTests",
            dependencies: [
                "EntID",
                "EntIDTestee",
                "EntIDWire",
                .product(name: "SwiftProtobuf", package: "swift-protobuf"),
            ],
            swiftSettings: strictSwiftSettings
        ),
    ]
)
