/// A tiny indented source writer.
///
/// The emitter formats its own output rather than relying on a formatter being
/// installed: generated code is committed, and a diff that moves because a tool
/// version changed hides the rule that actually changed.
struct SwiftSource {
    private(set) var text = ""
    private var depth = 0

    mutating func line(_ content: String = "") {
        if content.isEmpty {
            text += "\n"
        } else {
            text += String(repeating: "    ", count: depth) + content + "\n"
        }
    }

    mutating func lines(_ content: [String]) {
        for item in content { line(item) }
    }

    mutating func push() { depth += 1 }
    mutating func pop() { depth -= 1 }

    mutating func header(summary: String, detail: String) {
        // The emitter owns the shape of what it writes. A formatter run over
        // generated code would make a rules update diff as a formatting change,
        // which is exactly what committing the generated code exists to avoid.
        line("// Generated by entid-gen. Do not edit by hand.")
        line("// swift-format-ignore-file")
        line("// swiftlint:disable all")
        line("//")
        line("// \(summary)")
        for paragraph in detail.split(separator: "\n", omittingEmptySubsequences: false) {
            line("// \(paragraph)".trimmingTrailingSpaces())
        }
        line()
    }

    /// A Swift string literal for arbitrary text.
    ///
    /// Anything outside printable ASCII is escaped as `\u{...}` so that the
    /// emitted file stays pure ASCII and cannot change meaning through an
    /// invisible code point.
    static func quote(_ text: String) -> String {
        var out = "\""
        for scalar in text.unicodeScalars {
            switch scalar {
            case "\\": out += "\\\\"
            case "\"": out += "\\\""
            case "\n": out += "\\n"
            case "\t": out += "\\t"
            case "\r": out += "\\r"
            default:
                if scalar.value >= 0x20, scalar.value < 0x7F {
                    out.unicodeScalars.append(scalar)
                } else {
                    out += "\\u{\(String(scalar.value, radix: 16, uppercase: true))}"
                }
            }
        }
        return out + "\""
    }
}

extension String {
    func trimmingTrailingSpaces() -> String {
        var result = self
        while result.hasSuffix(" ") { result.removeLast() }
        return result
    }
}
