#!/usr/bin/env bash
# Line coverage.
#
# `engine.md` section 12.2 asks for at least 95% of lines, and since 2026.08.26
# it says which lines: the ones somebody wrote. The thresholds therefore cover
# the hand written code — the engine, its primitives, its API, its generator —
# and nothing else.
#
# The code emitted from the bundle is measured and printed, never gated. Its
# coverage is a property of the corpus, not of this engine: an unexecuted rule
# branch says no conformance case reaches it, which the unused-operation report
# already says better. Gating on it would fail a faultless engine on a gap in
# the corpus, and the only way back to green would be to lower the threshold.
#
# The Protobuf code generated by protoc-gen-swift is excluded everywhere, which
# section 12.2 allows with the exclusion documented: this project does not write
# it either.
set -euo pipefail

LIBRARY_MINIMUM=${LIBRARY_MINIMUM:-95}
PACKAGE_MINIMUM=${PACKAGE_MINIMUM:-95}

cd "$(dirname "$0")/.."

swift test --enable-code-coverage "$@" >/dev/null

PROFDATA=$(find .build -name default.profdata -print -quit)
BINARY=$(find .build -name 'EntIDPackageTests.xctest' -print -quit)/Contents/MacOS/EntIDPackageTests
if [ ! -f "$BINARY" ]; then
  BINARY=$(find .build -name '*PackageTests.xctest' -print -quit)
fi

coverage() {
  xcrun llvm-cov report "$BINARY" -instr-profile="$PROFDATA" -ignore-filename-regex="$1" \
    | tail -1 | awk '{ gsub(/%/, "", $10); print $10 }'
}

# Written by nobody here: the Protobuf plumbing, the tests, the build tree, and
# the code entid-gen emits from the bundle.
NOT_OURS='(Tests/|\.build/|EntIDWire/Generated|Sources/EntID/Generated)'
LIBRARY=$(coverage "${NOT_OURS}|Sources/EntIDGenerator|Sources/EntIDConformance|Sources/EntIDTestee")
PACKAGE=$(coverage "${NOT_OURS}")

# Measured and published, deliberately not gated.
EMITTED=$(xcrun llvm-cov report "$BINARY" -instr-profile="$PROFDATA" Sources/EntID/Generated \
  | tail -1 | awk '{ gsub(/%/, "", $10); print $10 }')

printf 'hand written library line coverage: %s%% (minimum %s%%)\n' "$LIBRARY" "$LIBRARY_MINIMUM"
printf 'hand written package line coverage: %s%% (minimum %s%%)\n' "$PACKAGE" "$PACKAGE_MINIMUM"
printf 'emitted rule code line coverage:    %s%% (measured, not gated)\n' "$EMITTED"

fail=0
awk -v value="$LIBRARY" -v minimum="$LIBRARY_MINIMUM" 'BEGIN { exit !(value >= minimum) }' || {
  echo "the shipped library is below its coverage gate" >&2
  fail=1
}
awk -v value="$PACKAGE" -v minimum="$PACKAGE_MINIMUM" 'BEGIN { exit !(value >= minimum) }' || {
  echo "the package is below its coverage gate" >&2
  fail=1
}
exit $fail
