#!/usr/bin/env bash
# Line coverage gates.
#
# `engine.md` section 12.2 asks for at least 95% of lines. Two numbers are
# reported: the shipped library, which is what a consumer runs, and the whole
# package, which includes the generator and the conformance plumbing. Neither
# excludes a critical file: the only thing left out of the second number is the
# Protobuf code generated by protoc-gen-swift, which this project does not write
# and which section 12.2 allows excluding with the exclusion documented.
set -euo pipefail

LIBRARY_MINIMUM=${LIBRARY_MINIMUM:-95}
PACKAGE_MINIMUM=${PACKAGE_MINIMUM:-95}

cd "$(dirname "$0")/.."

swift test --enable-code-coverage "$@" >/dev/null

PROFDATA=$(find .build -name default.profdata -print -quit)
BINARY=$(find .build -name 'BusinessIDPackageTests.xctest' -print -quit)/Contents/MacOS/BusinessIDPackageTests
if [ ! -f "$BINARY" ]; then
  BINARY=$(find .build -name '*PackageTests.xctest' -print -quit)
fi

coverage() {
  xcrun llvm-cov report "$BINARY" -instr-profile="$PROFDATA" -ignore-filename-regex="$1" \
    | tail -1 | awk '{ gsub(/%/, "", $10); print $10 }'
}

NOT_OURS='(Tests/|\.build/|BusinessIDWire/Generated)'
LIBRARY=$(coverage "${NOT_OURS}|Sources/BusinessIDGenerator|Sources/BusinessIDConformance|Sources/BusinessIDTestee")
PACKAGE=$(coverage "${NOT_OURS}")

printf 'shipped library line coverage: %s%% (minimum %s%%)\n' "$LIBRARY" "$LIBRARY_MINIMUM"
printf 'whole package line coverage:   %s%% (minimum %s%%)\n' "$PACKAGE" "$PACKAGE_MINIMUM"

fail=0
awk -v value="$LIBRARY" -v minimum="$LIBRARY_MINIMUM" 'BEGIN { exit !(value >= minimum) }' || {
  echo "the shipped library is below its coverage gate" >&2
  fail=1
}
awk -v value="$PACKAGE" -v minimum="$PACKAGE_MINIMUM" 'BEGIN { exit !(value >= minimum) }' || {
  echo "the package is below its coverage gate" >&2
  fail=1
}
exit $fail
